io.snappydata.hydra.testDMLOps.SnappySchemaPrms-createSchemas = "create schema app";

io.snappydata.hydra.testDMLOps.SnappySchemaPrms-createTablesStatements =
"create table app.persoon (id bigint primary key ,firstName varchar(30) ,middleName varchar(30) ,lastName varchar(30) ,title varchar(5) ,address varchar(40) ,country varchar(10) ,phone varchar(12) ,dateOfBirth varchar(15) ,age int ,status varchar(10) ,email varchar(30) ,education varchar(20) ,occupation varchar(15))"
;

io.snappydata.hydra.testDMLOps.SnappySchemaPrms-tablesList =
"app.persoon"
;
