io.snappydata.hydra.snapshotIsolation.SnapshotIsolationPrms-snappyDDLExtn =
" USING row OPTIONS(PERSISTENT 'sync')"
" USING row OPTIONS(PERSISTENT 'sync')"
" USING row OPTIONS(PERSISTENT 'sync')"
" USING row OPTIONS(PERSISTENT 'sync')"
" USING row OPTIONS(PERSISTENT 'sync')"
" USING row OPTIONS(PERSISTENT 'sync')"
" USING row OPTIONS(PERSISTENT 'sync')"
" USING row OPTIONS(PERSISTENT 'sync')"
" USING row OPTIONS(PERSISTENT 'sync')"
" USING row OPTIONS(PERSISTENT 'sync')"
" USING row OPTIONS(PERSISTENT 'sync')"
;