SELECT PRSN_ID, CLM_ID,CLM_DTL_ID,VER,CLIENT_ID,DIAG_CD_ID,CLM_CHRG_AMT,DEDUCTABLE_AMT FROM CLAIM_DETAIL WHERE CLIENT_ID = ? AND CLM_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? );
SELECT PRSN_ID, CLM_ID,CLM_DTL_ID,VER,CLIENT_ID,DIAG_CD_ID,CLM_CHRG_AMT,DEDUCTABLE_AMT FROM CLAIM_DETAIL WHERE CLIENT_ID = ? AND CLM_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
SELECT PRSN_ID, CLM_ID,CLM_DTL_ID,VER,CLIENT_ID,DIAG_CD_ID,CLM_CHRG_AMT,DEDUCTABLE_AMT FROM CLAIM_DETAIL WHERE CLIENT_ID = ? AND CLM_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
SELECT PRSN_ID, CLM_ID,CLM_DTL_ID,VER,CLIENT_ID,DIAG_CD_ID,CLM_CHRG_AMT,DEDUCTABLE_AMT FROM CLAIM_DETAIL WHERE CLIENT_ID = ? AND CLM_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
SELECT *  FROM CODE_VALUE WHERE CLIENT_ID = ? AND CD_VAL_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? );
SELECT ORG_ID, VER, CLIENT_ID, ORG_NM, ORG_TYP_REF_ID, CAST(DESCR AS VARCHAR(32672)) AS DESCR, EMPR_TAX_ID, WEB_SITE, EFF_DT, EXPR_DT, VLD_FRM_DT, VLD_TO_DT, ORG_STAT,CAST(SRC_SYS_REF_ID AS VARCHAR(32672)) AS SRC_SYS_REF_ID,
CAST(SRC_SYS_REC_ID AS VARCHAR(32672)) AS SRC_SYS_REC_ID FROM ORGANIZATIONS WHERE CLIENT_ID = ? AND ORG_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ;
SELECT ORG_ID, VER, CLIENT_ID, ORG_NM, ORG_TYP_REF_ID, CAST(DESCR AS VARCHAR(32672)) AS DESCR, EMPR_TAX_ID, WEB_SITE, EFF_DT, EXPR_DT, VLD_FRM_DT, VLD_TO_DT, ORG_STAT,CAST(SRC_SYS_REF_ID AS VARCHAR(32672)) AS SRC_SYS_REF_ID,
CAST(SRC_SYS_REC_ID AS VARCHAR(32672)) AS SRC_SYS_REC_ID FROM ORGANIZATIONS WHERE CLIENT_ID = ? AND ORG_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ;
SELECT ORG_ID, VER, CLIENT_ID, ORG_NM, ORG_TYP_REF_ID, CAST(DESCR AS VARCHAR(32672)) AS DESCR, EMPR_TAX_ID, WEB_SITE, EFF_DT, EXPR_DT, VLD_FRM_DT, VLD_TO_DT, ORG_STAT,CAST(SRC_SYS_REF_ID AS VARCHAR(32672)) AS SRC_SYS_REF_ID,
CAST(SRC_SYS_REC_ID AS VARCHAR(32672)) AS SRC_SYS_REC_ID FROM ORGANIZATIONS WHERE CLIENT_ID = ? AND ORG_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ;
SELECT *  FROM CODE_VALUE WHERE CLIENT_ID = ? AND CD_VAL_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? );
SELECT *  FROM CONTACT WHERE CLIENT_ID = ? AND CNTC_TYP_REF_ID = ? AND CNTC_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
SELECT *  FROM CONTACT WHERE CLIENT_ID = ? AND CNTC_TYP_REF_ID = ? AND CNTC_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? );
SELECT *  FROM CONTACT WHERE CLIENT_ID = ? AND CNTC_TYP_REF_ID = ? AND CNTC_ID IN ( ?, ?, ?, ?, ?, ?, ?, ? );
SELECT *  FROM CODE_VALUE WHERE CLIENT_ID = ? AND CD_VAL_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? );
SELECT PRSN_ID, CLM_ID, SEQ_NUM, CLM_DTL_ID, VER, CLIENT_ID, CAST(LN_OF_BUS AS VARCHAR(32672)) AS LN_OF_BUS, CAST(LN_OF_BUS_IND AS VARCHAR(32672)) AS LN_OF_BUS_IND,
CAST(CAP_FND_ID AS VARCHAR(32672)) AS CAP_FND_ID, CAST(CAP_POOL_ID AS VARCHAR(32672)) AS CAP_POOL_ID, POS_CD_ID, PR_CD_ID,DIAG_CD_ID, RLTD_DIAG_CD_ID,
CAST(CUR_CLM_STAT_CD AS VARCHAR(32672)) AS CUR_CLM_STAT_CD, SERV_FRM_DT, SERV_TO_DT, CAST(RM_TYP_ID AS VARCHAR(32672)) AS RM_TYP_ID,CLM_CHRG_AMT,
CAST(ANES_MOD AS VARCHAR(32672)) AS ANES_MOD, CLM_RT_AMT, ALWD_AMT, CONSIDERED_AMT, NUM_OF_UNT, ALWD_NUM_OF_UNT, DEDUCTABLE_AMT, COPAY_AMT,
COINSURANCE_AMT, RISK_WHLD_AMT, CLM_PD_AMT, DISALLOW_AMT, EXPLAIN_CD_ID, DISALLOW_EXPLAIN_CD, AGREE_PRC, DISC_AMT, SUPPL_DISC_AMT, ITS_DISC_AMT,
CAST(PRVD_NTWK_STAT AS VARCHAR(32672)) AS PRVD_NTWK_STAT, CAST(REF_IND AS VARCHAR(32672)) AS REF_IND, CAST(PRE_AUTH_IND AS VARCHAR(32672)) AS PRE_AUTH_IND,
CAST(CAPITATED_SVIND AS VARCHAR(32672)) AS CAPITATED_SVIND, SUBS_PAY, PRVD_PAY, PRE_PD_AMT, CAST(SERV_RPT_CAT AS VARCHAR(32672)) AS SERV_RPT_CAT,
CAST(EXPER_CAT AS VARCHAR(32672)) AS EXPER_CAT, CAST(ACCT_CAT AS VARCHAR(32672)) AS ACCT_CAT, CAST(REF_ID AS VARCHAR(32672)) AS REF_ID, REF_SEQ_NUM,
CAST(PRE_AUTH_ID AS VARCHAR(32672)) AS PRE_AUTH_ID, PRE_AUTH_SEQ_NUM, CAST(PRE_AUTH_SRC AS VARCHAR(32672)) AS PRE_AUTH_SRC, CAST(IO_IND AS VARCHAR(32672)) AS IO_IND,
CAST(AMBUL_PAY_CD AS VARCHAR(32672)) AS AMBUL_PAY_CD, CAST(AMBUL_PAY_STAT AS VARCHAR(32672)) AS AMBUL_PAY_STAT, CLM_837_SEQ_NUM, CAST(MED_UTIL_EDIT_IND AS VARCHAR(32672)) AS MED_UTIL_EDIT_IND,
SBMT_DIAG_CD, SBMT_RLTD_DIAG_CD, TRNSLT_DIAG_CD, TRNSLT_RLTD_DIAG_CD, PRVD_SPECIALTY, PRVD_ID, VLD_FRM_DT, VLD_TO_DT, REF_REF_ID, PRE_AUTH_REF_ID,CAST(SRC_SYS_REF_ID AS VARCHAR(32672)) AS SRC_SYS_REF_ID,
CAST(SRC_SYS_REC_ID AS VARCHAR(32672)) AS SRC_SYS_REC_ID, REV_CD_ID, SERV_CD_ID FROM CLAIM_DETAIL WHERE CLIENT_ID = ? AND CLM_ID IN ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? );
SELECT ORG_ID, VER, CLIENT_ID, ORG_NM, ORG_TYP_REF_ID, CAST(DESCR AS VARCHAR(32672)) AS DESCR, EMPR_TAX_ID, WEB_SITE, EFF_DT, EXPR_DT, VLD_FRM_DT, VLD_TO_DT, ORG_STAT,
CAST(SRC_SYS_REF_ID AS VARCHAR(32672)) AS SRC_SYS_REF_ID,CAST(SRC_SYS_REC_ID AS VARCHAR(32672)) AS SRC_SYS_REC_ID  FROM ORGANIZATIONS WHERE CLIENT_ID = ? AND ORG_ID IN ( ?, ?, ?, ?, ?, ?, ?, ? );
SELECT *  FROM CONTACT WHERE CLIENT_ID = ? AND CNTC_TYP_REF_ID = ? AND CNTC_ID IN ( ?, ?, ?, ?, ?, ?, ?, ? );
SELECT *  FROM CONTACT WHERE CLIENT_ID = ? AND CNTC_TYP_REF_ID = ? AND CNTC_ID IN ( ?, ?, ?, ?, ?, ?, ?, ? );
SELECT PRSN_ID, VER, CLIENT_ID, CAST(TTL AS VARCHAR(32672)) AS TTL, CAST(FIRST_NM AS VARCHAR(32672)) AS FIRST_NM, CAST(LAST_NM AS VARCHAR(32672)) AS LAST_NM,
CAST(MID_NM AS VARCHAR(32672)) AS MID_NM, CAST(SFX AS VARCHAR(32672)) AS SFX, BIRTH_DT, GNDR_REF_ID, ETHN_REF_ID, MAR_STAT_REF_ID, LANG_REF_ID, PRSN_STAT_REF_ID, EFF_DT,
EXPR_DT, ATTACH_SRC_ID, VLD_FRM_DT, VLD_TO_DT, CAST(SRC_SYS_REF_ID AS VARCHAR(32672)) AS SRC_SYS_REF_ID, CAST(SRC_SYS_REC_ID AS VARCHAR(32672)) AS SRC_SYS_REC_ID,
CAST(SUPPL_ID AS VARCHAR(32672)) AS SUPPL_ID  FROM PERSONS WHERE CLIENT_ID = ? AND PRSN_ID IN ( ?, ?, ?, ?, ?, ?, ? );
SELECT PRSN_ID, VER, CLIENT_ID, CAST(TTL AS VARCHAR(32672)) AS TTL, CAST(FIRST_NM AS VARCHAR(32672)) AS FIRST_NM, CAST(LAST_NM AS VARCHAR(32672)) AS LAST_NM,
CAST(MID_NM AS VARCHAR(32672)) AS MID_NM, CAST(SFX AS VARCHAR(32672)) AS SFX, BIRTH_DT, GNDR_REF_ID, ETHN_REF_ID, MAR_STAT_REF_ID, LANG_REF_ID, PRSN_STAT_REF_ID, EFF_DT,
EXPR_DT, ATTACH_SRC_ID, VLD_FRM_DT, VLD_TO_DT, CAST(SRC_SYS_REF_ID AS VARCHAR(32672)) AS SRC_SYS_REF_ID, CAST(SRC_SYS_REC_ID AS VARCHAR(32672)) AS SRC_SYS_REC_ID,
CAST(SUPPL_ID AS VARCHAR(32672)) AS SUPPL_ID  FROM PERSONS WHERE CLIENT_ID = ? AND PRSN_ID IN ( ?, ?, ?, ?, ?, ?, ? );
SELECT PRSN_ID, VER, CLIENT_ID, CAST(TTL AS VARCHAR(32672)) AS TTL, CAST(FIRST_NM AS VARCHAR(32672)) AS FIRST_NM, CAST(LAST_NM AS VARCHAR(32672)) AS LAST_NM,
CAST(MID_NM AS VARCHAR(32672)) AS MID_NM, CAST(SFX AS VARCHAR(32672)) AS SFX, BIRTH_DT, GNDR_REF_ID, ETHN_REF_ID, MAR_STAT_REF_ID, LANG_REF_ID, PRSN_STAT_REF_ID, EFF_DT,
EXPR_DT, ATTACH_SRC_ID, VLD_FRM_DT, VLD_TO_DT, CAST(SRC_SYS_REF_ID AS VARCHAR(32672)) AS SRC_SYS_REF_ID, CAST(SRC_SYS_REC_ID AS VARCHAR(32672)) AS SRC_SYS_REC_ID,
CAST(SUPPL_ID AS VARCHAR(32672)) AS SUPPL_ID  FROM PERSONS WHERE CLIENT_ID = ? AND PRSN_ID IN ( ?, ?, ?, ?, ?, ?, ? );
SELECT PRSN_ID, VER, CLIENT_ID, CAST(TTL AS VARCHAR(32672)) AS TTL, CAST(FIRST_NM AS VARCHAR(32672)) AS FIRST_NM, CAST(LAST_NM AS VARCHAR(32672)) AS LAST_NM,
CAST(MID_NM AS VARCHAR(32672)) AS MID_NM, CAST(SFX AS VARCHAR(32672)) AS SFX, BIRTH_DT, GNDR_REF_ID, ETHN_REF_ID, MAR_STAT_REF_ID, LANG_REF_ID, PRSN_STAT_REF_ID, EFF_DT,
EXPR_DT, ATTACH_SRC_ID, VLD_FRM_DT, VLD_TO_DT, CAST(SRC_SYS_REF_ID AS VARCHAR(32672)) AS SRC_SYS_REF_ID, CAST(SRC_SYS_REC_ID AS VARCHAR(32672)) AS SRC_SYS_REC_ID,
CAST(SUPPL_ID AS VARCHAR(32672)) AS SUPPL_ID  FROM PERSONS WHERE CLIENT_ID = ? AND PRSN_ID IN ( ?, ?, ?, ?, ?, ?, ? );
SELECT *  FROM CODE_VALUE WHERE CLIENT_ID = ? AND CD_VAL_ID IN ( ?, ?, ?, ?, ?, ? );
SELECT *  FROM CODE_VALUE WHERE CLIENT_ID = ? AND CD_VAL_ID IN ( ?, ?, ?, ?, ?, ? );
SELECT *  FROM CODE_VALUE WHERE CLIENT_ID = ? AND CD_VAL_ID IN ( ?, ?, ?, ?, ?, ? );
SELECT *  FROM POSTAL_ADDRESS WHERE CLIENT_ID = ? AND CNTC_ID IN ( ?, ?, ?, ?, ? ) ;
SELECT *  FROM POSTAL_ADDRESS WHERE CLIENT_ID = ? AND CNTC_ID IN ( ?, ?, ?, ?, ? ) ;
SELECT *  FROM POSTAL_ADDRESS WHERE CLIENT_ID = ? AND CNTC_ID IN ( ?, ?, ?, ?, ? ) ;
SELECT *  FROM PHONE WHERE CLIENT_ID = ? AND CNTC_ID IN ( ?, ?, ?, ? );
SELECT *  FROM CONTACT WHERE CLIENT_ID = ? AND CNTC_ID IN ( ?, ?, ?, ? );
SELECT *  FROM CONTACT WHERE CLIENT_ID = ? AND CNTC_ID IN ( ?, ?, ?, ? );
SELECT *  FROM CONTACT WHERE CLIENT_ID = ? AND CNTC_ID IN ( ?, ?, ?, ? );
SELECT *  FROM BENEFIT_GROUPS WHERE CLIENT_ID = ? AND BENE_GRP_ID IN ( ?, ?, ? );
SELECT *  FROM CONTACT WHERE CLIENT_ID = ? AND CNTC_ID IN ( ?, ? );
SELECT *  FROM CONTACT WHERE CLIENT_ID = ? AND CNTC_ID IN ( ?, ?, ? );
SELECT *  FROM ORGANIZATION_CONTACT_TYPE WHERE CLIENT_ID = ? AND CNTC_TYP_REF_ID = ? AND ORG_ID IN (?, ?, ?);
SELECT EXPLAIN_CD_ID, VER, CLIENT_ID, CAST(EXPLAIN_TYP AS VARCHAR(32672)) AS EXPLAIN_TYP, CAST(EXPLAIN_STAT AS VARCHAR(32672)) AS EXPLAIN_STAT,
CAST(SD AS VARCHAR(32672)) AS SD, CAST(LD_1 AS VARCHAR(32672)) AS LD_1, CAST(LD_2 AS VARCHAR(32672)) AS LD_2, CAST(EXPLAIN_LBLTY_IND AS VARCHAR(32672)) AS EXPLAIN_LBLTY_IND,
CAST(EDI_CLM_STAT_CAT AS VARCHAR(32672)) AS EDI_CLM_STAT_CAT, CAST(EDI_CLM_STAT AS VARCHAR(32672)) AS EDI_CLM_STAT, CAST(EDI_CLM_ADJ_RSN AS VARCHAR(32672)) AS EDI_CLM_ADJ_RSN,
CAST(REM_RMRK AS VARCHAR(32672)) AS REM_RMRK, CAST(PRVD_ADJ_RSN AS VARCHAR(32672)) AS PRVD_ADJ_RSN,
CAST(HC_PLCY_ID AS VARCHAR(32672)) AS HC_PLCY_ID, VLD_FRM_DT, VLD_TO_DT, SRC_SYS_REF_ID, SRC_SYS_REC_ID  FROM EXPLANATION_CODE WHERE CLIENT_ID = ? AND EXPLAIN_CD_ID IN ( ?, ?, ? );
SELECT *  FROM CONTACT_TYPE_CONTACT WHERE CLIENT_ID = ? AND ORG_CNTC_TYP_ID IN ( ?, ? );
SELECT *  FROM GROUPS WHERE CLIENT_ID = ? AND GRP_TYP_REF_ID = ? AND GRP_ID IN ( ?, ? );
SELECT *  FROM ORGANIZATION_CODE WHERE CLIENT_ID = ? AND ORG_ID IN (?, ?, ?);
SELECT *  FROM ORGANIZATION_CODE WHERE CLIENT_ID = ? AND ORG_ID IN (?, ?);
SELECT *  FROM ORGANIZATION_CODE WHERE CLIENT_ID = ? AND ORG_ID IN (?, ?);
SELECT *  FROM ORGANIZATION_CODE WHERE CLIENT_ID = ? AND ORG_ID IN (?);
SELECT *  FROM BENEFIT_GROUPS WHERE CLIENT_ID = ? AND BENE_GRP_ID IN ( ?, ? );
SELECT *  FROM BENEFIT_GROUPS WHERE CLIENT_ID = ? AND BENE_GRP_ID IN ( ?, ? );
SELECT *  FROM BENEFIT_GROUPS WHERE CLIENT_ID = ? AND BENE_GRP_ID IN ( ?, ?, ? );
SELECT *  FROM CLAIM_COSHARE_TRACKING WHERE CLAIM_ID = ? AND LINE_NO = ? AND PRSN_ID = ? AND CLIENT_ID = ? ;
SELECT *  FROM CODE_VALUE WHERE CD_TYP_REF_ID = ? AND CLIENT_ID = ? AND CD_VAL_ID IN ( ? );
SELECT *  FROM CODE_VALUE WHERE CD_VAL = ? AND CD_TYP_REF_ID = ? AND CLIENT_ID = ?;
SELECT *  FROM FDI_CORRESPONDENCE WHERE ENTITY_ID = ? AND CLIENT_ID = ?;
SELECT PRSN_ID, CLM_ID, SEQ_NUM, CLM_STAT_ID, VER, CLIENT_ID, CAST(CLM_STAT_CD AS VARCHAR(32672)) AS CLM_STAT_CD, CAST(CUR_ITS_STAT_CD AS VARCHAR(32672)) AS CUR_ITS_STAT_CD, CLM_STAT_TS, STAT_RSN_REF_ID, CAST(USR_ID AS VARCHAR(32672)) AS USR_ID,
CAST(ROUTED_USR_ID AS VARCHAR(32672)) AS ROUTED_USR_ID, VLD_FRM_DT, VLD_TO_DT, SRC_SYS_REF_ID, SRC_SYS_REC_ID  FROM CLAIM_STATUS WHERE SEQ_NUM = ? AND PRSN_ID = ? AND CLIENT_ID = ? AND CLM_ID = ?;
SELECT *  FROM MOOP_BALANCE WHERE PRSN_ID = ? AND CLIENT_ID = ? ;
SELECT *  FROM PERSON_CONTACT WHERE CLIENT_ID = ? AND PRSN_ID IN ( ? );
SELECT *  FROM PERSON_RELATION WHERE PRSN_ID = ? AND RELN_TYP_REF_ID = ? AND CLIENT_ID = ?;
SELECT *  FROM PERSON_RELATION WHERE RELN_TYP_REF_ID = ? AND CLIENT_ID = ? AND PRSN_ID IN ( ? );
SELECT *  FROM PERSON_RELATION WHERE RELN_TYP_REF_ID = ? AND CLIENT_ID = ? AND RLTD_PRSN_ID IN ( ? );
SELECT *  FROM PERSON_ROLE WHERE PRSN_ID = ? AND CLIENT_ID = ? AND PRSN_TYP_REF_ID = ?;
SELECT *  FROM REVENUE_CODE WHERE CLIENT_ID = ? AND REV_CD_ID = ? ;















