-- DROP TABLE IF ALREADY EXISTS --
DROP TABLE IF EXISTS STAGING_AIRLINEREF;
DROP TABLE IF EXISTS AIRLINEREF;

----- CREATE TEMP TABLE -----
CREATE TABLE STAGING_AIRLINEREF
 (
   CODE VARCHAR(25),
   DESCRIPTION VARCHAR(25)
 ) 
 USING parquet OPTIONS(path '../../quickstart/data/airportcodeParquetData');

----- CREATE ROW TABLE -----

CREATE TABLE AIRLINEREF USING row OPTIONS() AS (SELECT * FROM STAGING_AIRLINEREF);
