SELECT * FROM ADJUSTMENT              WHERE   ADJ_ID = ? ;
SELECT * FROM BANK                    WHERE   BNK_ID = ?;
SELECT * FROM BANK_ACCOUNT            WHERE   BNK_ACCT_ID = ?;
SELECT * FROM BENEFIT_GROUP_NAME      WHERE   BENE_GRP_NM_ID = ?;
SELECT * FROM BENEFIT_GROUPS          WHERE   BENE_GRP_ID = ?;
SELECT * FROM BENEFIT_PACKAGE         WHERE   BENE_PKG_ID = ?;