SELECT * FROM ADJUSTMENT WHERE adj_id < 10;
SELECT * FROM ADJUSTMENT WHERE adj_id BETWEEN 100 AND 1000;
SELECT * FROM CODE_VALUE WHERE CLIENT_ID = ? AND CD_VAL_ID IN ( ?, ?, ?, ?, ?, ?, ?, ? );
SELECT ORG_ID, VER, CLIENT_ID, ORG_NM, ORG_TYP_REF_ID, CAST(DESCR AS VARCHAR(32672)) AS DESCR, EMPR_TAX_ID, WEB_SITE, EFF_DT, EXPR_DT, VLD_FRM_DT, VLD_TO_DT, ORG_STAT, CAST(SRC_SYS_REF_ID AS VARCHAR(32672)) AS SRC_SYS_REF_ID, CAST(SRC_SYS_REC_ID AS VARCHAR(32672)) AS SRC_SYS_REC_ID FROM ORGANIZATIONS WHERE CLIENT_ID = ? AND ORG_ID IN ( ?, ?, ? );
