io.snappydata.hydra.testDMLOps.SnappySchemaPrms-snappyDDLExtn =
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
" USING row OPTIONS(PERSISTENT '${persistenceMode}')"
;

INCLUDE $JTESTS/io/snappydata/hydra/testDMLOps/nwTablesDDLWithPK.inc;