SELECT * FROM testL1 WHERE id 30000 AND 40000
SELECT * FROM testL2 WHERE id 40000 AND 50000
SELECT * FROM testL3 WHERE id 50000 AND 60000
SELECT * FROM call_center;
SELECT * FROM CATALOG_PAGE;
SELECT * FROM CATALOG_RETURNS WHERE
SELECT * FROM CATALOG_SALES WHERE
SELECT * FROM CUSTOMER WHERE
SELECT * FROM CUSTOMER_ADDRESS WHERE
SELECT * FROM CUSTOMER_DEMOGRAPHICS WHERE
SELECT * FROM DATE_DIM WHERE
SELECT * FROM HOUSEHOLD_DEMOGRAPHICS;
SELECT * FROM INCOME_BAND;
SELECT * FROM INVENTORY WHERE
SELECT * FROM ITEM;
SELECT * FROM PROMOTION;
SELECT * FROM REASON;
SELECT * FROM SHIP_MODE;
SELECT * FROM STORE;
SELECT * FROM STORE_RETURNS WHERE
SELECT * FROM STORE_SALES WHERE
SELECT * FROM TIME_DIM WHERE
SELECT * FROM WAREHOUSE;
SELECT * FROM WEB_PAGE;
SELECT * FROM WEB_RETURNS WHERE
SELECT * FROM WEB_SALES WHERE
SELECT * FROM WEB_SITE;
