SELECT * FROM testL1 WHERE id BETWEEN 30000 AND 40000
SELECT * FROM testL2 WHERE id BETWEEN 40000 AND 50000
SELECT * FROM testL3 WHERE id BETWEEN 50000 AND 60000
SELECT * FROM call_center;
SELECT * FROM CATALOG_PAGE;
SELECT * FROM HOUSEHOLD_DEMOGRAPHICS;
SELECT * FROM INCOME_BAND;
SELECT * FROM ITEM;
SELECT * FROM PROMOTION;
SELECT * FROM REASON;
SELECT * FROM SHIP_MODE;
SELECT * FROM STORE;
SELECT * FROM WAREHOUSE;
SELECT * FROM WEB_PAGE;
SELECT * FROM WEB_SITE;
