#!/bin/sh

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This script is taken from 
# https://github.com/amplab/spark-ec2/blob/branch-1.6/spark-ec2
# with modifications.

# Preserve the user's CWD so that relative paths are passed correctly to 
#+ the underlying Python script.
SNAPPY_EC2_DIR="$(dirname "$0")"

python -Wdefault "${SNAPPY_EC2_DIR}/snappy_ec2.py" "$@"
