io.snappydata.hydra.cluster.SnappyPrms-expectedExceptions =
"java.net.BindException"
"NoSuchObjectException"
"NucleusObjectNotFoundException"
"RegionDestroyedException"
"DistributedSystemDisconnectedException"
"newDisconnectedException"
"CacheClosedException"
"java.io.FileNotFoundException"
"org.apache.spark.shuffle.FetchFailedException"
"org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor"
"java.lang.reflect.InvocationTargetException"
"org.apache.spark.storage.ShuffleBlockFetcherIterator.throwFetchFailedException"
"org.apache.spark.SparkException: Exception thrown in awaitResult"
"com.gemstone.gemfire.distributed.LockServiceDestroyedException"
"Failed to retrieve information for"
;

io.snappydata.hydra.cluster.SnappyPrms-expectedExceptionsForHA =
""
""

;

/*
io.snappydata.hydra.cluster.SnappyPrms-suspectStrings =
"java.lang.IllegalStateException"
"NullPointerException"
;
*/