io.snappydata.hydra.cluster.SnappyPrms-expectedExceptions =
"java.net.BindException"
"NoSuchObjectException"
"NucleusObjectNotFoundException"
"RegionDestroyedException"
"DistributedSystemDisconnectedException"
"newDisconnectedException"
"CacheClosedException"
"java.io.FileNotFoundException"
"org.apache.spark.shuffle.FetchFailedException"
"org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor"
"java.lang.reflect.InvocationTargetException"
"org.apache.spark.storage.ShuffleBlockFetcherIterator.throwFetchFailedException"
"org.apache.spark.SparkException: Exception thrown in awaitResult"
"com.gemstone.gemfire.distributed.LockServiceDestroyedException"
"Failed to retrieve information for"
"WARN LeadImpl: Exception while starting lead node"
;

io.snappydata.hydra.cluster.SnappyPrms-expectedExceptionsForHA =
"java.lang.reflect.InvocationTargetException"
"java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext"
;

io.snappydata.hydra.cluster.SnappyPrms-knownExceptionsForHA =
"java.net.ConnectException: Connection refused"
"Caused by: org.apache.thrift.transport.TTransportException: Failed to create or configure socket."
;


/*
io.snappydata.hydra.cluster.SnappyPrms-suspectStrings =
"java.lang.IllegalStateException"
"NullPointerException"
;
*/