io.snappydata.hydra.security.SnappySecurityPrms-isSecurity = ONEOF true true FOENO;
//io.snappydata.hydra.cluster.SnappyPrms-locatorLauncherProps = " -server-auth-provider=NONE ";
//io.snappydata.hydra.cluster.SnappyPrms-serverLauncherProps = " -server-auth-provider=NONE ";
//io.snappydata.hydra.cluster.SnappyPrms-leaderLauncherProps = " -server-auth-provider=NONE ";
io.snappydata.hydra.security.SnappySecurityPrms-passFile = /export/dev9a/users/spillai/snappydata/dtests/src/test/java/io/snappydata/hydra/cluster/commonPassFile.txt;
