/*
 * Copyright (c) 2007-2018, Marketo, Inc. All rights reserved.
 * See https://developers.marketo.com/MunchkinLicense.pdf for license terms
 * Marketo marketing automation web activity tracking script
 * Version: 154 r672
 */
 (function(l){if(!l.MunchkinTracker){var k=l.document,n=k.location,y=encodeURIComponent,z=[],s=function(b,a,c,d){try{var g=function(){try{c.apply(this,arguments)}catch(a){}};b.addEventListener?b.addEventListener(a,g,d||!1):b.attachEvent&&b.attachEvent("on"+a,g);z.push([b,a,g,d])}catch(e){}},N=function(b,a,c,d){try{b.removeEventListener?b.removeEventListener(a,c,d||!1):b.detachEvent&&b.detachEvent("on"+a,c)}catch(g){}},e=function(b){return"undefined"!==typeof b&&null!==b},A=function(b,a){return b.className.match(RegExp("(\\s|^)"+
a+"(\\s|$)"))},O=e(l.XMLHttpRequest)&&e((new l.XMLHttpRequest).withCredentials),q=function(b){var a=null,c;if(e(b))if(0===b.length)a="";else try{a=decodeURIComponent(b)}catch(d){c=b.indexOf("?");if(-1!==c)try{a=decodeURIComponent(b.substr(0,c))+b.substr(c)}catch(g){}e(a)||(a=String(b))}return a},B=function(b,a){var c={},d=e(a)?a:"=",g=b.split("&"),f=g.length,h,m,k;for(h=0;h<f;h+=1)m=g[h].split(d),e(m)&&1<m.length&&(k=m.shift(),m=m.join(d),c[q(k)]=q(m));return c},C=function(b){try{var a=k.createElement("a");
a.href=b;return B(a.search.substr(1))}catch(c){return null}},D=function(b,a){var c=null,d=[];if(e(b))for(c in b)b.hasOwnProperty(c)&&"function"!==typeof b[c]&&null!==b[c]&&d.push(y(c)+(e(a)?a:"=")+y(b[c]));return d.join("&")},E=function(b,a){var c=null;if(e(a)&&e(b))for(c in b)b.hasOwnProperty(c)&&e(a[c])&&(b[c]=a[c])},u=function(b){var a=k.cookie,c,d,g={id:null,token:null};b=y(b);g.store=function(a,c,d,g){var e=b+"="+D(this,":"),h=new Date;0<a?h.setTime(h.getTime()+864E5*a):h.setTime(h.getTime()-
1);e+="; expires="+h.toGMTString();c&&(e+="; path="+c);d&&-1!==d.indexOf(".")&&(e+="; domain="+d);g&&(e+="; secure");k.cookie=e};if(""!==a)for(a=a.split(";"),c=0;c<a.length;c+=1)if(d=a[c].replace(/^\s+|\s+$/g,""),0===d.indexOf(b+"=")){a=d.substring(b.length+1);c=B(a);e(c.id)&&e(c.token)?E(g,c):E(g,B(a,":"));break}return g},h={customName:null,notifyPrefix:null,wsInfo:null,altIds:[],visitorToken:null,cookieLifeDays:730,clickTime:350,cookieAnon:!0,mkt_tok:null,domainLevel:null,replayDetectLimit:5E3,
httpsOnly:!1,asyncOnly:!1,anonymizeIP:!1},F=null,p=null,P=l.navigator.cookieEnabled||k.hasOwnProperty("cookie")&&(0<k.cookie.length||-1<(k.cookie="testcookie=test; max-age=10000").indexOf.call(k.cookie,"testcookie=test;")),w=!1,x=[],G=null,Q=function(b,a,c){var d=new l.XMLHttpRequest;d.open("GET",b,!0!==a);d.onreadystatechange=function(){2<=d.readyState&&d.abort()};if(a)try{d.timeout=c}catch(e){}try{d.send()}catch(f){}},J=function(b,a,c,d,e){b=b+a+"&"+D(c)+"&"+D(d);c=(new Date).getTime();e=!e&&!h.asyncOnly;
0===a.indexOf("webevents/visitWebPage?")&&(e=!1);O?Q(b,e,h.clickTime):(new l.Image(1,1)).src=b;G=c+h.clickTime},R=function(){var b;return function(a,c){var d={x:a.clientX,y:a.clientY,el:c,time:(new Date).getTime()};if(e(b)&&d.x===b.x&&d.y===b.y&&d.el===b.el&&d.time<b.time+h.replayDetectLimit)return!0;b=d;return!1}}(),K=function(){var b=k.getElementsByName("_mkt_trk"),a=0,c="";e(p)&&(c="id:"+p.id+"&token:"+p.token);for(a=0;a<b.length;a+=1)"hidden"===b[a].type&&(b[a].value=c)},t=function(b,a,c,d){var g=
null,f;f=n.hostname;var k=n.protocol,m="webevents/"+b;if(!w)x.push(["post",arguments]);else if(e(p)&&(a._mchId=p.id,a._mchTk=p.token,e(h.mkt_tok)&&(a.mkt_tok=h.mkt_tok),e(h.wsInfo)&&(a._mchWs=h.wsInfo),"clickLink"===b&&(a._mchCn=e(h.customName)?h.customName:""),a._mchHo=f,a._mchPo=n.port,e(a._mchRu)||(a._mchRu=q(n.pathname)),a._mchPc=k,a._mchVr="154",e(f)&&0!==f.length&&"file:"!==k))for(g in h.anonymizeIP&&(a.aip=1),m+="?_mchNc="+(new Date).getTime(),J(h.notifyPrefix,m,a,c,d),h.altIds)h.altIds.hasOwnProperty(g)&&
(f=h.altIds[g],a._mchId=f,J(h.notifyPrefix.replace(/\w{3}\-\w{3}\-\w{3}\.mktoresp\.com/i,f+".mktoresp.com"),m,a,c,d))},L=function(b){var a=b||l.event,c=a.target||a.srcElement,d={},g;g=a.which;var f=a.button;g=e(g)&&(1===g||2===g)||e(f)&&(0===f||1===f||4===f)?!0:!1;if(g&&!a._mchDone){a._mchDone=!0;a=c;g=n.href||n;for(-1<g.indexOf("#")&&(g=g.substring(0,g.indexOf("#")));"A"!==a.tagName&&"AREA"!==a.tagName&&e(a.parentNode);)a=a.parentNode;a===k||a===l||"A"!==a.tagName&&"AREA"!==a.tagName?a=null:(c=a.href.replace(/^\s+|\s+$/g,
""),a=e(c)&&0<c.length&&0!==c.indexOf("#")&&0!==c.indexOf(g+"#")&&0!==c.indexOf("javascript")&&0!==c.indexOf("mailto")&&!A(a,"mchNoDecorate")?a:null);e(a)&&!R(b,a)&&(d._mchHr=q(a.href),t("clickLink",d))}},v=function(b){if(w){if(null!==p)return p;var a;a:{a=n.hostname;var c=h.domainLevel,d=a.split("."),g=d.length,f=2;if(e(c))f=c;else if(2<d[g-1].length)f=2;else if(2===d[g-1].length)f=3;else break a;for(;d.length>f&&2<d.length;)d.shift();a=d.join(".")}c=u("_mkto_trk");d=!1!==h.httpsOnly;if(e(c.id)||
h.cookieAnon||b){if(c.id=F,e(c.token)||(e(h.visitorToken)&&"VISITOR_MKTTOK_REPLACE"!==h.visitorToken?c.token=h.visitorToken:c.token="_mch-"+a+"-"+(new Date).getTime()+"-"+(Math.floor(9E4*Math.random())+1E4)),c.store(h.cookieLifeDays,"/",a,d),d&&(c=u("_mkto_trk")),!d||e(c.id))return p=c,K(),c}else return null}else x.push(["createTrackingCookie",arguments])},M=function(){v(!0)},S=function(b){var a=b.onclick;b.onclick="function"===typeof a?function(){M.apply(b,arguments);return a.apply(b,arguments)}:
M},H=function(b){var a=u("mkto_opt_out"),c=!1!==h.httpsOnly;b?(a.id=!0,a.store(730,"/",n.hostname,c),b=u("_mkto_trk"),b.id&&b.store(0,"/",n.hostname,c)):a.store(0,"/",n.hostname,c)},I={ASSOCIATE_LEAD:"associateLead",CLICK_LINK:"clickLink",VISIT_WEB_PAGE:"visitWebPage",init:function(b,a){if(P&&e(b)&&0!==b.length){F=b;var c="",d,g,f;d=C(l.location.toString());var r=null;h.notifyPrefix=n.protocol+"//"+F+".mktoresp.com/";e(a)&&E(h,a);e(d)&&(e(d.mkt_tok)&&(h.mkt_tok=d.mkt_tok),e(d.lpview)&&(c=d.lpview),
e(d.marketo_opt_out)&&(r=d.marketo_opt_out));if(!e(h.mkt_tok))if(d=C(k.referrer),e(d.mkt_tok))h.mkt_tok=d.mkt_tok;else if(e(d.enid)&&e(d.type))for(f in d)d.hasOwnProperty(f)&&"enid"!==f&&"type"!==f&&(-1<f.indexOf("mkt_tok")||-1<d[f].indexOf("mkt_tok"))&&(g=C(f+"="+d[f]),e(g.mkt_tok)&&(h.mkt_tok=g.mkt_tok));if("preview"!==c||!/\/lpeditor\/preview$/.test(n.pathname)){if(null===r){if(c=u("mkto_opt_out"),e(c.id)){H(!0);return}}else{if("true"===r){H(!0);return}"false"===r&&H(!1)}if(!w){w=!0;c=v(e(h.mkt_tok));
r={};for(d={};0<x.length;)switch(f=x.shift(),f[0]){case "createTrackingCookie":c=v.apply(k,f[1]);break;case "post":t.apply(k,f[1])}if(e(c))r._mchCn=e(h.customName)?h.customName:"",d._mchHa=q(n.hash),d._mchRe=q(k.referrer),d._mchQp=q(n.search.substr(1).replace(/&/g,"__-__")),t("visitWebPage",r,d,!0);else if(!(h.cookieAnon||e(l.Mkto)&&e(l.Mkto.formSubmit))){c=[];f=k.forms;var r=f.length,m,p;for(d=0;d<r;d+=1)if(A(f[d],"lpeRegForm"))for(m=f[d].elements,p=m.length,g=0;g<p;g+=1)"submit"!==m[g].type||A(m[g],
"mchNoDecorate")||c.push(m[g]);for(f=0;f<c.length;f+=1)S(c[f])}}}}},munchkinFunction:function(b,a,c){var d={},g={},f=null;e(c)&&(d._mchKy=c);switch(b){case "associateLead":for(f in a)a.hasOwnProperty(f)&&(d["_mchAt"+f]=a[f]);v(!0);t("associateLead",d);break;case "clickLink":e(a.href)&&(d._mchHr=d._mchLr=q(a.href));t("clickLink",d);break;case "visitWebPage":e(a.url)&&(d._mchRu=q(a.url)),e(a.params)&&(d._mchQp=q(a.params.replace(/&/g,"__-__"))),e(a.name)&&(d._mchCn=a.name),g._mchRe=q(n.href),t("visitWebPage",
d,g)}},createTrackingCookie:function(b){v(b)}};Date.prototype.getTimeAlias=Date.prototype.getTime;s(l,"beforeunload",function(){for(var b;0<z.length;)b=z.shift(),N.apply(this,b);if(e(G)){do b=new Date;while(b.getTimeAlias()<G)}});s(k,"click",L,!0);(function(b){var a=!1,c=!0,d=k.documentElement,e=function(c){"readystatechange"===c.type&&"complete"!==k.readyState||a||(a=!0,b.call(l,c.type||c))},f=null,f=function(){try{d.doScroll("left")}catch(a){l.setTimeout(f,50);return}e("poll")};if("complete"===
k.readyState)b.call(l,"lazy");else{if(k.createEventObject&&d.doScroll){try{c=!l.frameElement}catch(h){}c&&f()}s(k,"DOMContentLoaded",e);s(k,"readystatechange",e);s(l,"load",e)}})(function(){K();var b=0;if(e(k.links))for(b=0;b<k.links.length;b+=1)s(k.links[b],"click",L,!0)});l.MunchkinTracker=l.Munchkin=I;l.mktoMunchkin=I.init;l.mktoMunchkinFunction=I.munchkinFunction}})(window);
