#!/usr/bin/env sh
#set -vx

# This script helps to simulate twitter stream as a file stream. It copies
# tweet files from one folder to another folder on which a file stream can be
# created for about 10 mins.

if [ $# -ne 0 ]; then
    echo "ERROR: incorrect argument specified: " "$@"
    echo "Usage:./simulateHitachiFileStream.sh"
    exit 1
fi

# Removing directories from user specified location if exists and creating new ones.
rm -rf /tmp/ACC/*
rm -rf /tmp/BIO/*
rm -rf /tmp/ENV/*


# Copy csv to a folder to simulate a file stream.
count=0
start=$(date +%s%3N)
end=$((start+200000))
while [ "$start" -lt "$end" ]; do
start=$(date +%s%3N)
count=$((count+1))
accfile=/home/swati/hitachi/zip/question0131_details/data/test_src1_1.csv
echo "Copying csv file $accfile in /tmp/ACC/test_src1$count"
cp $accfile /tmp/ACC/"test_src1_"$count".csv"
sleep 0.4
biofile=/home/swati/hitachi/zip/question0131_details/data/test_src2_1.csv
echo "Copying csv file $biofile in /tmp/BIO/test_src2$count"
cp $biofile /tmp/BIO/"test_src2_"$count".csv"
sleep 0.4
envfile=/home/swati/hitachi/zip/question0131_details/data/test_src3_1.csv
echo "Copying csv file $envfile in /tmp/ENV/test_src3$count"
cp $envfile /tmp/ENV/"test_src3_"$count".csv"
sleep 0.4
done
sleep 1
echo "Data copying done"

